---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - urlshortener.tapsi.ir
  resources:
  - shorturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - urlshortener.tapsi.ir
  resources:
  - shorturls/finalizers
  verbs:
  - update
- apiGroups:
  - urlshortener.tapsi.ir
  resources:
  - shorturls/status
  verbs:
  - get
  - patch
  - update
