apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: url-shortener-operator-system
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: url-shortener-operator-system
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
